### ISSUE TITLE
[Feature request] Add command to MoonDeck decky plugin

### ISSUE THREAD

**Issue by Dudu514** [FrogTheFrog/moondeck-buddy#42]
Hi, with linux support, it would be great to have a command in the MoonDeck decky plugin, at the same place as "Restart PC", "Shutdown PC" etc... to restart the Sunshine process if needed. 

For headless server, it would be easier to control the sunshine process from the MoonDeck plugin.

Thanks.

**Comment by FrogTheFrog** [comment]
After initial analysis it seems too much effort for too little.

On linux there is no support for restarting it yet via the web API, while on Windows there is. I can send an interrupt signal to process on linux, but not on Windows (only KILL) which would result in a messy restart.

Since there is no easy and straightforward solution, I don't think I will spend any time on this given that it would be a very rarely used feature (I never had to restart Sunshine, for example, but not saying that you're the only who needs this).

If you're willing to work on this, please reopen the issue, otherwise I recommend creating a shortcut in sunshine to restart the process via `pkill` or something and use MoonDeck to sync the shortcut to the deck.
