### ISSUE TITLE
Can't quit game on host

### ISSUE THREAD

**Issue by saviu-u** [FrogTheFrog/moondeck-buddy#68]
Hi, I have a issue where whenever I want to quit a game on host (and on client of course) I have to either:
- Quit the game by their own menus (not ideal sometimes)
or
- Kill the entire steam session by killing stream process via Moondeck menu option
(Forcing the steam to shutdown wouldn't be such an issue if the steam cloud save wouldn't botter me on the next time I want to open a game)

Usually in moonlight what I would do is to use "Quit app on host PC after ending stream", which, indeed kills the moonbuddy as it seems, but does not kill the game itself, could it also take the game process down with it? I am not sure if the application is saving the PID from the game, I assume it does because if I quit the game on its own menu, the moondeck also quits from steam deck (not sure if it's how it works)

Is there any other way to quit the game on host which I am not aware of? if not, then it's a feature request to force the game to shutdown when the buddy instance dies on the host machine (or at least add as a feature)

**Comment by FrogTheFrog** [comment]
Quitting the game manually is the only correct way to do it.

Buddy, does not observe the PID of the game (as there can be multiple PIDs if you include the launchers) and instead relies on Steam's metadata that is saved when the game is started/closed.

On linux, it would be kinda doable, but not on Windows as it literally kills the game process without allowing it to do a proper shutdown (the same happens when you close Steam). Therefore this feature will not be implemented.
