### ISSUE TITLE
Support for non-steam games?

### ISSUE THREAD

**Issue by chaserileyroberts** [FrogTheFrog/moondeck-buddy#84]
Whats the technical hurdle?

**Comment by FrogTheFrog** [comment]
Initially the hurdle was that I thought that there is no way to get info about running non-Steam games from Steam. It seems that there might be logs that could be parsed, so now the biggest hurdle for me is time (I'm not willing to spend time on it since I won't be using non-Steam shortcuts at all).

If you, or anyone wants to submit the PR feel free to do so. I can already tell there will be a lot of work:

1. Rewrite detection logic to properly log files and determine whether the logs entries are valid for the currently running Steam instance (instead of using Windows registry or process tree on Linux).
2. Parse the `shortcuts.vdf` to get the info about them.
3. Sync the shortcuts from Buddy to MoonDeck (should be easy enough as already doing something similar with Sunshine apps).

**Comment by joeknock90** [comment]
DISCLAIMER:

I am not a programmer or developer of any sort. I can mess around in bash and that's about it. I am a Linux admin by trade. The last time I worked in an actual programming language in any real capacity was in college, which is further in the past than I'd like to admit.

Using the vdf library i wrote this little script to dump shortcuts.vdf to a json file:

```
import vdf
import json

# Read the binary shortcuts.vdf file
with open("shortcuts.vdf", "rb") as vdf_file:
    shortcuts_data = vdf.binary_load(vdf_file)

# Convert the parsed data to JSON and save it to a file
with open("shortcuts.json", "w", encoding="utf-8") as json_file:
    json.dump(shortcuts_data, json_file, indent=4)
```

In this example I have stardew valley installed from GOG via Heroic Games Launcher and added as a steam shortcut, giving this output

shortcuts.json
```
{
  "shortcuts": {
    "0": {
      "appid": -1811634022,
      "AppName": "Stardew Valley",
      "Exe": "\"/opt/Heroic/heroic\"",
      "StartDir": "\"/home/joe\"",
      "icon": "/home/joe/Games/Heroic/Stardew Valley/support/icon.png",
      "ShortcutPath": "",
      "LaunchOptions": "--no-gui --no-sandbox \"heroic://launch/gog/1453375253\"",
      "IsHidden": 0,
      "AllowDesktopConfig": 1,
      "AllowOverlay": 1,
      "OpenVR": 0,
      "Devkit": 0,
      "DevkitGameID": "",
      "DevkitOverrideAppID": 0,
      "LastPlayTime": 1723138095,
      "FlatpakAppID": "",
      "tags": {}
    }
  }
}

```

Would this help at all or am I just doing something everyone already knows how to do and am wasting people's time?

**Comment by FrogTheFrog** [comment]
I'm playing around with the first blocker issue at the moment. If this one can be resolved successfully, it will be a smooth sailing from that point.

While I appreciate your enthusiasm, not help is needed for now.

**Comment by joeknock90** [comment]
Glad to hear it. It really does just come from enthusiasm! Steam remote play is barely functional on Linux hosts and moonlight is excellent but slightly less integrated. 

MoonDeckBuddy really does tie it all together. Thanks for your excellent work!
